name: domain
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Müller Patrice  <mueller.patrice@gmail.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  meta: ^1.1.6
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  mockito: ^3.0.0
